In [1]:
print("All Okay")

All Okay


In [2]:
import torch

In [3]:
print(torch.__version__)

2.5.1+cpu


In [4]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [5]:
if torch.cuda.is_available():
    print('cuda')

In [6]:
torch.empty(2,3)

tensor([[-1.7356e-18,  1.7670e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [7]:
a = torch.empty(2,3)
print(a)

tensor([[-1.7357e-18,  1.7670e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [8]:
type(a)

torch.Tensor

In [9]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [11]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(3,4)

tensor([[7.6473e-01, 9.1467e-01, 9.3613e-01, 1.7121e-01],
        [5.5441e-02, 5.3226e-01, 7.4960e-01, 1.6765e-01],
        [1.1629e-04, 6.2808e-01, 1.1359e-01, 9.8567e-02]])

In [13]:
torch.rand(3,4)

tensor([[0.6207, 0.0951, 0.2180, 0.2401],
        [0.5605, 0.0389, 0.1838, 0.1625],
        [0.6372, 0.9897, 0.2164, 0.1629]])

In [14]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [15]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [16]:
torch.Tensor([[2,3,4],[4,5,6],[4,3,8]])

tensor([[2., 3., 4.],
        [4., 5., 6.],
        [4., 3., 8.]])

In [17]:
torch.tensor([[2,3,4],[4,5,6],[4,3,8]])

tensor([[2, 3, 4],
        [4, 5, 6],
        [4, 3, 8]])

In [19]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
torch.arange(3,10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [21]:
torch.arange(3,10,2)

tensor([3, 5, 7, 9])

In [22]:
torch.linspace(1,20,10)

tensor([ 1.0000,  3.1111,  5.2222,  7.3333,  9.4444, 11.5556, 13.6667, 15.7778,
        17.8889, 20.0000])

In [23]:
torch.linspace(1,10,20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [24]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [26]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [28]:
x = torch.tensor([[2,3,4],[4,2,1]])

In [29]:
x.shape

torch.Size([2, 3])

In [30]:
torch.empty_like(x)

tensor([[5418671804016,             0,             0],
        [            0,             0,             0]])

In [31]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [34]:
torch.rand_like(x, dtype=float)

tensor([[0.6327, 0.5669, 0.3390],
        [0.9199, 0.6169, 0.5496]], dtype=torch.float64)

In [35]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.0108, 0.0343, 0.1212],
        [0.0490, 0.0310, 0.7192]])

In [36]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.4534, 0.1549, 0.7622],
        [0.6014, 0.4512, 0.1309]], dtype=torch.float64)

In [37]:
x

tensor([[2, 3, 4],
        [4, 2, 1]])

In [38]:
x+2

tensor([[4, 5, 6],
        [6, 4, 3]])

In [39]:
x-2

tensor([[ 0,  1,  2],
        [ 2,  0, -1]])

In [40]:
x/2

tensor([[1.0000, 1.5000, 2.0000],
        [2.0000, 1.0000, 0.5000]])

In [41]:
x*2

tensor([[4, 6, 8],
        [8, 4, 2]])

In [43]:
c=torch.tensor([1,-2,-7,-8,0])
c

tensor([ 1, -2, -7, -8,  0])

In [45]:
torch.abs(c)

tensor([1, 2, 7, 8, 0])

In [46]:
torch.neg(c)

tensor([-1,  2,  7,  8,  0])

In [51]:
d = torch.tensor([2.6,2.3,1.2])
d

tensor([2.6000, 2.3000, 1.2000])

In [52]:
torch.round(d)

tensor([3., 2., 1.])

In [53]:
torch.floor(d)

tensor([2., 2., 1.])

In [54]:
torch.ceil(d)

tensor([3., 3., 2.])

In [56]:
torch.randint(size=(3,4),low=3, high=9)

tensor([[4, 3, 8, 5],
        [3, 3, 5, 4],
        [5, 4, 8, 8]])

In [57]:
torch.randint(size=(3,4),low=3, high=9,dtype=torch.float16)

tensor([[3., 4., 5., 8.],
        [6., 3., 8., 5.],
        [5., 4., 5., 5.]], dtype=torch.float16)

In [58]:
e=torch.randint(size=(3,4),low=3, high=9,dtype=float)
e

tensor([[7., 6., 4., 3.],
        [5., 5., 4., 7.],
        [6., 4., 3., 6.]], dtype=torch.float64)

In [59]:
sum(e)

tensor([18., 15., 11., 16.], dtype=torch.float64)

In [60]:
torch.sum(e)

tensor(60., dtype=torch.float64)

In [61]:
torch.sum(e, dim=0)

tensor([18., 15., 11., 16.], dtype=torch.float64)

In [62]:
torch.sum(e, dim=1)

tensor([20., 21., 19.], dtype=torch.float64)

In [63]:
torch.mean(e, dim=1)

tensor([5.0000, 5.2500, 4.7500], dtype=torch.float64)

In [64]:
torch.mean(e, dim=0)

tensor([6.0000, 5.0000, 3.6667, 5.3333], dtype=torch.float64)

In [65]:
torch.mean(e)

tensor(5., dtype=torch.float64)

In [66]:
torch.min(e)

tensor(3., dtype=torch.float64)

In [67]:
torch.max(e)

tensor(7., dtype=torch.float64)

In [70]:
e

tensor([[7., 6., 4., 3.],
        [5., 5., 4., 7.],
        [6., 4., 3., 6.]], dtype=torch.float64)

In [ ]:
# gives the index of max value in matrix
torch.argmax(e)

tensor(0)

In [ ]:
# gives the index of min value in matrix
torch.argmin(e)

tensor(3)

In [74]:
f = torch.randint(size=(2,3),low=1,high=7)
f

tensor([[4, 5, 6],
        [1, 1, 3]])

In [76]:
g = torch.randint(size=(3,2), low=2,high=5)
g

tensor([[2, 2],
        [4, 4],
        [3, 4]])

In [77]:
torch.matmul(f,g)

tensor([[46, 52],
        [15, 18]])

In [80]:
vec1 = torch.tensor([5,2,3])
vec2 = torch.tensor([4,2,4])
vec1

tensor([5, 2, 3])

In [81]:
torch.dot(vec1, vec2)

tensor(36)

In [89]:
f = torch.randint(size=(2,3), low=1, high=4,dtype=torch.int)
f

tensor([[2, 1, 2],
        [2, 3, 2]], dtype=torch.int32)

In [93]:
torch.transpose(f)

TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


In [90]:
torch.transpose(f,0,1)

tensor([[2, 2],
        [1, 3],
        [2, 2]], dtype=torch.int32)

In [92]:
torch.transpose(f,1,0)

tensor([[2, 2],
        [1, 3],
        [2, 2]], dtype=torch.int32)

In [94]:
f

tensor([[2, 1, 2],
        [2, 3, 2]], dtype=torch.int32)

In [95]:
f

tensor([[2, 1, 2],
        [2, 3, 2]], dtype=torch.int32)

In [96]:
torch.inverse(f)

RuntimeError: linalg.inv: A must be batches of square matrices, but they are 2 by 3 matrices

In [98]:
h=torch.randint(size = (2,2), low=1, high=3)
h

tensor([[1, 2],
        [2, 2]])

In [99]:
torch.inverse(h)

RuntimeError: linalg.inv: Expected a floating point or complex tensor as input. Got Long

In [100]:
g = torch.rand(2,2)
g

tensor([[0.1977, 0.1699],
        [0.6641, 0.9510]])

In [101]:
torch.inverse(g)

tensor([[12.6416, -2.2582],
        [-8.8282,  2.6285]])

In [102]:
I = torch.randint(size=(3,2), low=1, high=5)
I

tensor([[3, 4],
        [4, 4],
        [2, 3]])

In [103]:
torch.log(I)

tensor([[1.0986, 1.3863],
        [1.3863, 1.3863],
        [0.6931, 1.0986]])

In [104]:
torch.exp(I)

tensor([[20.0855, 54.5981],
        [54.5981, 54.5981],
        [ 7.3891, 20.0855]])

In [106]:
torch.softmax(I)

TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype = None, *, Tensor out = None)
 * (Tensor input, name dim, *, torch.dtype dtype = None)


In [107]:
torch.softmax(I,0)

RuntimeError: "softmax_kernel_impl" not implemented for 'Long'

In [109]:
torch.softmax(g)

TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype = None, *, Tensor out = None)
 * (Tensor input, name dim, *, torch.dtype dtype = None)


In [111]:
g

tensor([[0.1977, 0.1699],
        [0.6641, 0.9510]])

In [110]:
torch.softmax(g,0)

tensor([[0.3855, 0.3141],
        [0.6145, 0.6859]])

# Backward Tensors

In [116]:
import torch
x = torch.tensor(2., requires_grad=True)
y = x**2
print(y.backward())

None


In [117]:
x.grad

tensor(4.)

In [118]:
import torch.nn as nn

# NOTE: nn.Module has a function "__call__", which helps in calling the class as a function

In [ ]:
class Model(nn.Module):
    def __init__(self, new_features):
        super().__init__()
        self.linear=nn.Linear(new_features,1) # 1 represents hidden layer
        self.sigmoid=nn.Sigmoid()
    def forward(self):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    


In [121]:
features = torch.rand(10,5)

In [122]:
features.shape

torch.Size([10, 5])

In [123]:
features.shape[1]

5

In [126]:
model = Model(features.shape[1])

In [129]:
model()

tensor([[0.6451],
        [0.7045],
        [0.6670],
        [0.6641],
        [0.6551],
        [0.6662],
        [0.6798],
        [0.6816],
        [0.6822],
        [0.6715]], grad_fn=<SigmoidBackward0>)

In [128]:
model.forward()

tensor([[0.6451],
        [0.7045],
        [0.6670],
        [0.6641],
        [0.6551],
        [0.6662],
        [0.6798],
        [0.6816],
        [0.6822],
        [0.6715]], grad_fn=<SigmoidBackward0>)