In [1]:
print("All Okay")

All Okay


In [2]:
import torch

In [3]:
print(torch.__version__)

2.5.1+cpu


In [4]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [5]:
if torch.cuda.is_available():
    print('cuda')

In [6]:
torch.empty(2,3)

tensor([[-1.7356e-18,  1.7670e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [7]:
a = torch.empty(2,3)
print(a)

tensor([[-1.7357e-18,  1.7670e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [8]:
type(a)

torch.Tensor

In [9]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [11]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(3,4)

tensor([[7.6473e-01, 9.1467e-01, 9.3613e-01, 1.7121e-01],
        [5.5441e-02, 5.3226e-01, 7.4960e-01, 1.6765e-01],
        [1.1629e-04, 6.2808e-01, 1.1359e-01, 9.8567e-02]])

In [13]:
torch.rand(3,4)

tensor([[0.6207, 0.0951, 0.2180, 0.2401],
        [0.5605, 0.0389, 0.1838, 0.1625],
        [0.6372, 0.9897, 0.2164, 0.1629]])

In [14]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [15]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [16]:
torch.Tensor([[2,3,4],[4,5,6],[4,3,8]])

tensor([[2., 3., 4.],
        [4., 5., 6.],
        [4., 3., 8.]])

In [17]:
torch.tensor([[2,3,4],[4,5,6],[4,3,8]])

tensor([[2, 3, 4],
        [4, 5, 6],
        [4, 3, 8]])

In [19]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
torch.arange(3,10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [21]:
torch.arange(3,10,2)

tensor([3, 5, 7, 9])

In [22]:
torch.linspace(1,20,10)

tensor([ 1.0000,  3.1111,  5.2222,  7.3333,  9.4444, 11.5556, 13.6667, 15.7778,
        17.8889, 20.0000])

In [23]:
torch.linspace(1,10,20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [24]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [26]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])