In [1]:
print("All Okay")

All Okay


In [2]:
import torch

In [3]:
print(torch.__version__)

2.5.1+cpu


In [4]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [5]:
if torch.cuda.is_available():
    print('cuda')

In [6]:
torch.empty(2,3)

tensor([[-1.7356e-18,  1.7670e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [7]:
a = torch.empty(2,3)
print(a)

tensor([[-1.7357e-18,  1.7670e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [8]:
type(a)

torch.Tensor

In [9]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [11]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(3,4)

tensor([[7.6473e-01, 9.1467e-01, 9.3613e-01, 1.7121e-01],
        [5.5441e-02, 5.3226e-01, 7.4960e-01, 1.6765e-01],
        [1.1629e-04, 6.2808e-01, 1.1359e-01, 9.8567e-02]])

In [13]:
torch.rand(3,4)

tensor([[0.6207, 0.0951, 0.2180, 0.2401],
        [0.5605, 0.0389, 0.1838, 0.1625],
        [0.6372, 0.9897, 0.2164, 0.1629]])

In [14]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [15]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [16]:
torch.Tensor([[2,3,4],[4,5,6],[4,3,8]])

tensor([[2., 3., 4.],
        [4., 5., 6.],
        [4., 3., 8.]])

In [17]:
torch.tensor([[2,3,4],[4,5,6],[4,3,8]])

tensor([[2, 3, 4],
        [4, 5, 6],
        [4, 3, 8]])

In [19]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
torch.arange(3,10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [21]:
torch.arange(3,10,2)

tensor([3, 5, 7, 9])

In [22]:
torch.linspace(1,20,10)

tensor([ 1.0000,  3.1111,  5.2222,  7.3333,  9.4444, 11.5556, 13.6667, 15.7778,
        17.8889, 20.0000])

In [23]:
torch.linspace(1,10,20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

In [24]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [26]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [28]:
x = torch.tensor([[2,3,4],[4,2,1]])

In [29]:
x.shape

torch.Size([2, 3])

In [30]:
torch.empty_like(x)

tensor([[5418671804016,             0,             0],
        [            0,             0,             0]])

In [31]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [34]:
torch.rand_like(x, dtype=float)

tensor([[0.6327, 0.5669, 0.3390],
        [0.9199, 0.6169, 0.5496]], dtype=torch.float64)

In [35]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.0108, 0.0343, 0.1212],
        [0.0490, 0.0310, 0.7192]])

In [36]:
torch.rand_like(x, dtype=torch.float64)

tensor([[0.4534, 0.1549, 0.7622],
        [0.6014, 0.4512, 0.1309]], dtype=torch.float64)

In [37]:
x

tensor([[2, 3, 4],
        [4, 2, 1]])

In [38]:
x+2

tensor([[4, 5, 6],
        [6, 4, 3]])

In [39]:
x-2

tensor([[ 0,  1,  2],
        [ 2,  0, -1]])

In [40]:
x/2

tensor([[1.0000, 1.5000, 2.0000],
        [2.0000, 1.0000, 0.5000]])

In [41]:
x*2

tensor([[4, 6, 8],
        [8, 4, 2]])

In [43]:
c=torch.tensor([1,-2,-7,-8,0])
c

tensor([ 1, -2, -7, -8,  0])

In [45]:
torch.abs(c)

tensor([1, 2, 7, 8, 0])

In [46]:
torch.neg(c)

tensor([-1,  2,  7,  8,  0])

In [51]:
d = torch.tensor([2.6,2.3,1.2])
d

tensor([2.6000, 2.3000, 1.2000])

In [52]:
torch.round(d)

tensor([3., 2., 1.])

In [53]:
torch.floor(d)

tensor([2., 2., 1.])

In [54]:
torch.ceil(d)

tensor([3., 3., 2.])

In [56]:
torch.randint(size=(3,4),low=3, high=9)

tensor([[4, 3, 8, 5],
        [3, 3, 5, 4],
        [5, 4, 8, 8]])

In [57]:
torch.randint(size=(3,4),low=3, high=9,dtype=torch.float16)

tensor([[3., 4., 5., 8.],
        [6., 3., 8., 5.],
        [5., 4., 5., 5.]], dtype=torch.float16)

In [58]:
e=torch.randint(size=(3,4),low=3, high=9,dtype=float)
e

tensor([[7., 6., 4., 3.],
        [5., 5., 4., 7.],
        [6., 4., 3., 6.]], dtype=torch.float64)

In [59]:
sum(e)

tensor([18., 15., 11., 16.], dtype=torch.float64)

In [60]:
torch.sum(e)

tensor(60., dtype=torch.float64)

In [61]:
torch.sum(e, dim=0)

tensor([18., 15., 11., 16.], dtype=torch.float64)

In [62]:
torch.sum(e, dim=1)

tensor([20., 21., 19.], dtype=torch.float64)

In [63]:
torch.mean(e, dim=1)

tensor([5.0000, 5.2500, 4.7500], dtype=torch.float64)

In [64]:
torch.mean(e, dim=0)

tensor([6.0000, 5.0000, 3.6667, 5.3333], dtype=torch.float64)

In [65]:
torch.mean(e)

tensor(5., dtype=torch.float64)

In [66]:
torch.min(e)

tensor(3., dtype=torch.float64)

In [67]:
torch.max(e)

tensor(7., dtype=torch.float64)

In [70]:
e

tensor([[7., 6., 4., 3.],
        [5., 5., 4., 7.],
        [6., 4., 3., 6.]], dtype=torch.float64)

In [ ]:
# gives the index of max value in matrix
torch.argmax(e)

tensor(0)

In [ ]:
# gives the index of min value in matrix
torch.argmin(e)

tensor(3)

In [74]:
f = torch.randint(size=(2,3),low=1,high=7)
f

tensor([[4, 5, 6],
        [1, 1, 3]])

In [76]:
g = torch.randint(size=(3,2), low=2,high=5)
g

tensor([[2, 2],
        [4, 4],
        [3, 4]])

In [77]:
torch.matmul(f,g)

tensor([[46, 52],
        [15, 18]])

In [80]:
vec1 = torch.tensor([5,2,3])
vec2 = torch.tensor([4,2,4])
vec1

tensor([5, 2, 3])

In [81]:
torch.dot(vec1, vec2)

tensor(36)

In [89]:
f = torch.randint(size=(2,3), low=1, high=4,dtype=torch.int)
f

tensor([[2, 1, 2],
        [2, 3, 2]], dtype=torch.int32)

In [93]:
torch.transpose(f)

TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


In [90]:
torch.transpose(f,0,1)

tensor([[2, 2],
        [1, 3],
        [2, 2]], dtype=torch.int32)

In [92]:
torch.transpose(f,1,0)

tensor([[2, 2],
        [1, 3],
        [2, 2]], dtype=torch.int32)

In [94]:
f

tensor([[2, 1, 2],
        [2, 3, 2]], dtype=torch.int32)

In [95]:
f

tensor([[2, 1, 2],
        [2, 3, 2]], dtype=torch.int32)

In [96]:
torch.inverse(f)

RuntimeError: linalg.inv: A must be batches of square matrices, but they are 2 by 3 matrices

In [98]:
h=torch.randint(size = (2,2), low=1, high=3)
h

tensor([[1, 2],
        [2, 2]])

In [99]:
torch.inverse(h)

RuntimeError: linalg.inv: Expected a floating point or complex tensor as input. Got Long

In [100]:
g = torch.rand(2,2)
g

tensor([[0.1977, 0.1699],
        [0.6641, 0.9510]])

In [101]:
torch.inverse(g)

tensor([[12.6416, -2.2582],
        [-8.8282,  2.6285]])

In [102]:
I = torch.randint(size=(3,2), low=1, high=5)
I

tensor([[3, 4],
        [4, 4],
        [2, 3]])

In [103]:
torch.log(I)

tensor([[1.0986, 1.3863],
        [1.3863, 1.3863],
        [0.6931, 1.0986]])

In [104]:
torch.exp(I)

tensor([[20.0855, 54.5981],
        [54.5981, 54.5981],
        [ 7.3891, 20.0855]])

In [106]:
torch.softmax(I)

TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype = None, *, Tensor out = None)
 * (Tensor input, name dim, *, torch.dtype dtype = None)


In [107]:
torch.softmax(I,0)

RuntimeError: "softmax_kernel_impl" not implemented for 'Long'

In [109]:
torch.softmax(g)

TypeError: softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype = None, *, Tensor out = None)
 * (Tensor input, name dim, *, torch.dtype dtype = None)


In [111]:
g

tensor([[0.1977, 0.1699],
        [0.6641, 0.9510]])

In [110]:
torch.softmax(g,0)

tensor([[0.3855, 0.3141],
        [0.6145, 0.6859]])

# Backward Tensors

In [116]:
import torch
x = torch.tensor(2., requires_grad=True)
y = x**2
print(y.backward())

None


In [117]:
x.grad

tensor(4.)

In [118]:
import torch.nn as nn

# NOTE: nn.Module has a function "__call__", which helps in calling the class as a function

In [ ]:
class Model(nn.Module):
    def __init__(self, new_features):
        super().__init__()
        self.linear=nn.Linear(new_features,1) # 1 represents hidden/output layer
        self.sigmoid=nn.Sigmoid()
    def forward(self):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out
    


In [121]:
features = torch.rand(10,5)

In [122]:
features.shape

torch.Size([10, 5])

In [123]:
features.shape[1]

5

In [126]:
model = Model(features.shape[1])

In [129]:
model()

tensor([[0.6451],
        [0.7045],
        [0.6670],
        [0.6641],
        [0.6551],
        [0.6662],
        [0.6798],
        [0.6816],
        [0.6822],
        [0.6715]], grad_fn=<SigmoidBackward0>)

In [128]:
model.forward()

tensor([[0.6451],
        [0.7045],
        [0.6670],
        [0.6641],
        [0.6551],
        [0.6662],
        [0.6798],
        [0.6816],
        [0.6822],
        [0.6715]], grad_fn=<SigmoidBackward0>)

In [131]:
model.linear.weight

Parameter containing:
tensor([[0.1640, 0.0118, 0.1215, 0.1605, 0.2528]], requires_grad=True)

In [132]:
model.linear.bias

Parameter containing:
tensor([0.3866], requires_grad=True)

## Neural Network with 3 hidden layer and 1 output layer

In [142]:
class Model(nn.Module):
    def __init__(self, new_features):
        super().__init__()
        self.linear1=nn.Linear(new_features, 3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self, features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out     



In [133]:
data=torch.rand(10,5)
data

tensor([[0.5389, 0.1374, 0.5477, 0.3275, 0.7865],
        [0.6799, 0.6732, 0.7291, 0.0673, 0.3265],
        [0.8176, 0.2634, 0.6723, 0.8519, 0.8730],
        [0.1252, 0.7138, 0.4799, 0.6463, 0.9510],
        [0.7514, 0.0149, 0.6148, 0.0662, 0.8553],
        [0.0783, 0.9949, 0.1470, 0.6852, 0.7261],
        [0.6676, 0.9709, 0.5891, 0.0288, 0.0266],
        [0.9986, 0.5949, 0.3930, 0.3573, 0.6570],
        [0.3750, 0.6539, 0.2184, 0.7481, 0.4097],
        [0.8838, 0.9515, 0.6427, 0.6286, 0.0431]])

In [136]:
data.shape[1]

5

In [143]:
model=Model(data.shape[1])
model

Model(
  (linear1): Linear(in_features=5, out_features=3, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=3, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)

In [146]:
model(data)  ## becuae of __call__ function we are getting this val

tensor([[0.6469],
        [0.6621],
        [0.6405],
        [0.6492],
        [0.6471],
        [0.6599],
        [0.6739],
        [0.6507],
        [0.6523],
        [0.6695]], grad_fn=<SigmoidBackward0>)

In [151]:
model.forward(data)

tensor([[0.6469],
        [0.6621],
        [0.6405],
        [0.6492],
        [0.6471],
        [0.6599],
        [0.6739],
        [0.6507],
        [0.6523],
        [0.6695]], grad_fn=<SigmoidBackward0>)

In [148]:
model.linear1.weight

Parameter containing:
tensor([[-0.1077, -0.1575, -0.1257, -0.1255,  0.3661],
        [ 0.3594, -0.3016, -0.4224,  0.2257, -0.2870],
        [ 0.2205,  0.0859, -0.1936,  0.0826, -0.3357]], requires_grad=True)

In [149]:
model.linear1.bias

Parameter containing:
tensor([0.0658, 0.3708, 0.3681], requires_grad=True)

In [152]:
model.linear2.weight

Parameter containing:
tensor([[ 0.2610, -0.2857,  0.4420]], requires_grad=True)

In [153]:
model.linear2.bias

Parameter containing:
tensor([0.5338], requires_grad=True)

In [ ]:
class Model(nn.module):
    def __init__(self, num_features):
        super.__init__()
        self.network=nn.Sequential(
            nn.linear(num_features,3),
            nn.ReLU(),
            nn.linear(3,1),
            nn.Sigmoid()
        )
    def forward(self,features):
        out=self.network(features)
        return out


In [154]:
model=Model(data.shape[1])
model(data)

tensor([[0.5646],
        [0.5551],
        [0.5553],
        [0.5537],
        [0.5873],
        [0.5521],
        [0.5512],
        [0.5693],
        [0.5533],
        [0.5432]], grad_fn=<SigmoidBackward0>)

In [155]:
from torchinfo import summary
summary(model,input=(10,5))

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

# Practice examples

In [162]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [ ]:

data = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [157]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [158]:
data = data.drop(columns=['id', 'Unnamed: 32'])
data.columns

Index(['diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [160]:
data['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [170]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:,1:], data.iloc[:,0],test_size=0.2)

In [173]:
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [174]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)
y_test

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1])

In [175]:
X_train

array([[ 0.18290588,  0.51940972,  0.1670428 , ...,  1.05214532,
         1.25672077,  1.37689117],
       [-0.35703164, -1.36348243, -0.37278098, ...,  0.02741266,
        -0.81779441,  0.09296505],
       [ 0.35510217,  1.35726258,  0.45752142, ...,  1.33888936,
         1.77534956,  0.80458393],
       ...,
       [ 2.68121139,  0.62186456,  2.56508164, ...,  1.82484505,
         1.08489542,  0.43398272],
       [-1.3365075 , -1.56383855, -1.32605972, ..., -0.77592341,
        -0.71060061, -0.32658349],
       [-0.19942826,  0.2757949 , -0.12598016, ...,  1.3796372 ,
         1.07858991,  1.45757359]], shape=(455, 30))

In [179]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [180]:
X_train_tensor.dtype

torch.float32

In [182]:
print(type(X_train))
print(type(X_train_tensor))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [190]:
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super.__init__()
        self.network=nn.Sequential(
            nn.linear(num_features,3),
            nn.ReLU(),
            nn.linear(3,1),
            nn.Sigmoid()
        )
    def forward(self,features):
        out=self.network(features)
        return out

In [195]:
class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()            
        )
    def forward(self,features):
        out=self.network(features)
        return out

In [193]:
X_train_tensor.shape[1]

30

In [198]:
learning_rate=0.01
epochs=25

In [203]:
loss_function=nn.BCELoss()

In [196]:
model = MySimpleNN(X_train_tensor.shape[1])

In [201]:
model.parameters()

<generator object Module.parameters at 0x00000206A0FE0CF0>

In [202]:
optimizer=torch.optim.SGD(model.parameters(), lr=learning_rate)

In [208]:
y_train_tensor


tensor([1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0.,
        1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
        1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
        1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0.,
        1., 0., 1., 0., 0., 0., 1., 0., 

In [209]:
y_train_tensor.view(-1,1)

tensor([[1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
      

In [211]:
for epoch in range(epochs):
    # forward pass
    y_pred = model(X_train_tensor)

    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    loss.backward()

    # parameters update
    optimizer.step()

    # print loss in each epoch
    print(f"epoch: {epoch+1}, Loss{loss.item()}")

epoch: 1, Loss0.6090058088302612
epoch: 2, Loss0.6076484322547913
epoch: 3, Loss0.6063035726547241
epoch: 4, Loss0.6049490571022034
epoch: 5, Loss0.6035827398300171
epoch: 6, Loss0.6021901369094849
epoch: 7, Loss0.6007679104804993
epoch: 8, Loss0.5993409752845764
epoch: 9, Loss0.5979103446006775
epoch: 10, Loss0.5964327454566956
epoch: 11, Loss0.5949553847312927
epoch: 12, Loss0.5934762358665466
epoch: 13, Loss0.5919972062110901
epoch: 14, Loss0.5905094742774963
epoch: 15, Loss0.5890202522277832
epoch: 16, Loss0.5875452160835266
epoch: 17, Loss0.586067259311676
epoch: 18, Loss0.5845697522163391
epoch: 19, Loss0.5830239057540894
epoch: 20, Loss0.5814779996871948
epoch: 21, Loss0.579935610294342
epoch: 22, Loss0.5783922076225281
epoch: 23, Loss0.5768569707870483
epoch: 24, Loss0.5753244757652283
epoch: 25, Loss0.5737771987915039


In [214]:
X_test_tensor.shape

torch.Size([114, 30])

In [215]:
X_test_tensor[1]

tensor([ 1.5132,  0.1146,  1.4053,  1.5164, -1.0532, -0.4580,  0.1472,  0.5624,
         0.3314, -1.5670,  0.6285, -1.0024,  0.4329,  0.8359, -0.8406, -0.7069,
        -0.2682, -0.0753,  0.0693, -0.7448,  1.2894, -0.4159,  1.1552,  1.2314,
        -1.1732, -0.7579, -0.1416,  0.3834,  0.2814, -1.6082])

In [216]:
model.forward(X_test_tensor[1])

tensor([0.3880], grad_fn=<SigmoidBackward0>)

In [217]:
y_pred=model.forward(X_test_tensor[1])
y_pred

tensor([0.3880], grad_fn=<SigmoidBackward0>)

In [218]:
y_pred=(y_pred>0.5).float()

In [219]:
y_test_tensor=y_test_tensor[0]

In [220]:
(y_pred==y_test_tensor).float()

tensor([1.])

In [212]:
with torch.no_grad():
    y_pred=model.forward(X_test_tensor)
    y_pred=(y_pred>0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6154201030731201


In [213]:
summary(model)

Layer (type:depth-idx)                   Param #
MySimpleNN                               --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       93
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       4
│    └─Sigmoid: 2-4                      --
Total params: 97
Trainable params: 97
Non-trainable params: 0